import 'loop_data.dart';

final Map<String, LoopData> uploads = {
  'Chill Vibes': LoopData(
    selectedTags: [],
    imagePath: 'assets/leavingroom.jpg',
    loopTitle: 'CHLL',
    artistName: 'Kyler',
    artistImagePath: 'assets/DSCF3834.JPEG',
    audioPath: 'assets/audio/Carhood.wav',
    licensing: 'assets/share.svg',
    comments: 120,
    likes: 450,
    hasBeenOnLeaderboard: true,
    pathToWaveForm: 'assets/waveforms/chill_vibes.png',
    dislikes: 10,
    tags: ['chill', 'vibes', 'relax', 'asdf', 'asdf', 'extremely long tag', 'shorter tag', 'short tag', 'vst'],
    location: 'Baton Rouge',
    topComment: 'This is so relaxing! my name is walter hartel white, i live at ',
  ),
  
  'Unsure': LoopData(
    selectedTags: [],
    imagePath: 'assets/IMG_4099.jpg',
    loopTitle: 'Unsure',
    artistName: 'Kyler',
    artistImagePath: 'assets/DSCF3834.JPEG',
    audioPath: 'assets/audio/Unsure.wav',
    licensing: 'assets/share.svg',
    comments: 150,
    likes: 500,
    hasBeenOnLeaderboard: true,
    pathToWaveForm: 'assets/waveforms/unsure.png',
    dislikes: 15,
    tags: ['unsure', 'mystery', 'cool'],
    location: 'Paris',
    topComment: 'Intriguing sounds!',
  ),

    'Midwest': LoopData(
    selectedTags: [],
    imagePath: 'assets/IMG_7924.jpg',
    loopTitle: 'Midwest Emo title that is unecessarily long',
    artistName: 'Kyler',
    artistImagePath: 'assets/DSCF3834.JPEG',
    audioPath: 'assets/audio/Midwest.wav',
    licensing: 'assets/share.svg',
    comments: 14,
    likes: 10,
    hasBeenOnLeaderboard: false,
    pathToWaveForm: 'assets/waveforms/_.png',
    dislikes: 0,
    tags: ['MWE', 'american football', 'picking '],
    location: 'New Orleans ',
    topComment: 'i like the ber ber ber part!',
  ),
};